### BUILD

.build:
  stage: build
  
  image: 
    name: "node:14.17.0"
    entrypoint: [""]

  script:
    - npm install
    - REACT_APP_BASE_URL=$REACT_APP_BASE_URL npm run build

  artifacts:
    paths:
      - build
    expire_in: 5 days

build:dev:
  extends: .build
  environment:
    name: dev
    action: prepare

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?/'
      when: on_success

build:prod:
  extends: .build
  environment:
    name: prod
    action: prepare

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?/'
      when: manual

### DEPLOY

.deploy:
  stage: deploy

  image: 
    name: amazon/aws-cli
    entrypoint: [""]

  script:
    - echo "Deploying to bucket $S3_BUCKET"
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 build dist s3://$S3_BUCKET --recursive --acl public-read

deploy:dev:
  extends: .deploy
  environment:
    name: dev
    action: prepare
  needs:
    - job: build:dev
      artifacts: true

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?/'
      when: on_success

deploy:prod:
  extends: .deploy
  environment:
    name: prod
    action: prepare
  needs:
    - job: build:prod
      artifacts: true

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?/'
      when: manual